frontend:
    image: dalynka/addorium-frontend:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`dalynkaa.me`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 2
    restart: always
